In [1]:
# binary classification with 5 features 
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)

        return out
      

In [2]:
features = torch.rand(10,5)
# create model

model = Model(features.shape[1])
# forward
model(features)

tensor([[0.6342],
        [0.5986],
        [0.6211],
        [0.5781],
        [0.5816],
        [0.5787],
        [0.5420],
        [0.6188],
        [0.6256],
        [0.6395]], grad_fn=<SigmoidBackward0>)

In [3]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.0873, -0.4075,  0.2339, -0.0555,  0.1560]], requires_grad=True)

In [4]:
model.linear.bias

Parameter containing:
tensor([0.3445], requires_grad=True)

In [5]:
!pip install torchinfo

In [6]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00