In [2]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id', 'Unnamed: 32'], inplace = True)

In [6]:
#  Train Test SPlit

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size = 0.2, random_state=42)
# random state makes the same train test split reproducible each time you run the code
# iloc means integer location based indexing that lets you select rows and columns using there indexes.

In [8]:
# scaling puts the features onto a comparable scale
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
# fit tranform means learn the scaling params from the data and scale the data
X_test = scaler.transform(X_test)

In [9]:
#  label encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [10]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,

In [11]:
X_test_tensor = torch.from_numpy(X_test)
y_test_tensor = torch.from_numpy(y_test)
y_train_tensor = torch.from_numpy(y_train)
X_train_tensor = torch.from_numpy(X_train)

In [12]:
X_train_tensor.shape

torch.Size([455, 30])

In [13]:
class MySimpleNN(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.Linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):

        out = self.Linear(features)
        out = self.sigmoid(out)  

        return out  
   

    def loss_function(self, y_pred, y_train_tensor):
        # clamp 
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        loss = -(y_train_tensor * torch.log(y_pred) + (1 -  y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss


In [14]:
# important parameters
learning_rate = 0.1
epochs = 25

In [15]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define the loop
for epoch in range(epochs):

    # forward pass
    y_pred = model(X_train_tensor)

    # loss calc
    loss = model.loss_function(y_pred, y_train_tensor)

    # backward pass
    loss.backward()

    # params update
    with torch.no_grad():
      model.linear.weight -= learning_rate * model.linear.weight.grad
      model.linear.bias -=  learning_rate * model.linear.bias.grad

    # zero gradients
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()
    
    print(f'Epoch: { epoch + 1}, Loss: { loss.item()}')



  


RuntimeError: mat1 and mat2 must have the same dtype, but got Double and Float

In [ ]:
model.weights

tensor([[ 2.8309e-02],
        [ 8.3820e-05],
        [-2.7474e-02],
        [-1.9377e-03],
        [-1.4230e-04],
        [ 1.7132e-03],
        [ 1.1079e-03],
        [ 2.2035e-04],
        [-5.6288e-05],
        [-3.4306e-04],
        [-1.7442e-03],
        [ 1.2654e-05],
        [ 2.0894e-03],
        [ 2.6550e-05],
        [ 7.6172e-06],
        [-5.2990e-05],
        [-3.6948e-04],
        [-1.6321e-04],
        [-1.4901e-04],
        [ 2.8066e-04],
        [-1.8251e-03],
        [-7.4890e-05],
        [-9.4107e-04],
        [ 2.0713e-03],
        [ 1.2065e-04],
        [-1.2251e-04],
        [ 9.3117e-06],
        [-2.0201e-04],
        [ 1.1254e-04],
        [-7.7517e-05]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([-0.5261], dtype=torch.float64, requires_grad=True)

In [ ]:
# model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred >  0.5).float()
    accuracy = ( y_pred == y_test_tensor).float().mean()
print(f'Accuracy: {accuracy.item()}')    



Accuracy: 0.6228070259094238
