In [62]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [63]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [64]:
df.shape

(569, 33)

In [65]:
df.drop(columns=['id', 'Unnamed: 32'], inplace = True)

In [66]:
#  Train Test SPlit

In [67]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size = 0.2, random_state=42)
# random state makes the same train test split reproducible each time you run the code
# iloc means integer location based indexing that lets you select rows and columns using there indexes.

In [68]:
# scaling puts the features onto a comparable scale
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
# fit tranform means learn the scaling params from the data and scale the data
X_test = scaler.transform(X_test)

In [69]:
#  label encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [70]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,

In [71]:
X_test_tensor = torch.from_numpy(X_test)
y_test_tensor = torch.from_numpy(y_test)
y_train_tensor = torch.from_numpy(y_train)
X_train_tensor = torch.from_numpy(X_train)

In [72]:
X_train_tensor.shape

torch.Size([455, 30])

In [73]:
class MySimpleNN():
    def __init__(self, X):

        self.weights = torch.rand(X.shape[1],1, dtype= torch.float64, requires_grad = True)
        self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)


    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y_train_tensor):
        # clamp 
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        loss = -(y_train_tensor * torch.log(y_pred) + (1 -  y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss


In [ ]:
# important parameters
learning_rate = 0.1
epochs = 100000

In [75]:
# create model
model = MySimpleNN(X_train_tensor)

# define the loop
for epoch in range(epochs):

    # forward pass
    y_pred = model.forward(X_train_tensor)

    # loss calc
    loss = model.loss_function(y_pred, y_train_tensor)

    # backward pass
    loss.backward()

    # params update
    with torch.no_grad():
      model.weights -= learning_rate * model.weights.grad
      model.bias -=  learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    
    print(f'Epoch: { epoch + 1}, Loss: { loss.item()}')



  


Epoch: 1, Loss: 3.8754937710855404
Epoch: 2, Loss: 3.7526051395093463
Epoch: 3, Loss: 3.625611405555518
Epoch: 4, Loss: 3.4958787017333273
Epoch: 5, Loss: 3.3627625081197334
Epoch: 6, Loss: 3.2254576144168747
Epoch: 7, Loss: 3.080252490273452
Epoch: 8, Loss: 2.9302370023918485
Epoch: 9, Loss: 2.7721017815485998
Epoch: 10, Loss: 2.6144640506659202
Epoch: 11, Loss: 2.455394746247932
Epoch: 12, Loss: 2.28946142746232
Epoch: 13, Loss: 2.1206998522970206
Epoch: 14, Loss: 1.9555179241293414
Epoch: 15, Loss: 1.7983060687196142
Epoch: 16, Loss: 1.6504901728972663
Epoch: 17, Loss: 1.5107481273908068
Epoch: 18, Loss: 1.3796304945714806
Epoch: 19, Loss: 1.263567128043727
Epoch: 20, Loss: 1.1641249473236062
Epoch: 21, Loss: 1.082013714022924
Epoch: 22, Loss: 1.0164720757543968
Epoch: 23, Loss: 0.9651708756245085
Epoch: 24, Loss: 0.9250490040359163
Epoch: 25, Loss: 0.893317377086031
Epoch: 26, Loss: 0.8678123518420021
Epoch: 27, Loss: 0.8469421912072257
Epoch: 28, Loss: 0.8295574012800706
Epoch: 29

In [76]:
model.weights

tensor([[-0.1036],
        [-0.0249],
        [ 0.1486],
        [ 0.2827],
        [ 0.0233],
        [-0.1165],
        [-0.0627],
        [ 0.0654],
        [-0.0195],
        [ 0.0492],
        [ 0.0687],
        [-0.0121],
        [ 0.1769],
        [-0.2259],
        [ 0.0116],
        [-0.0741],
        [ 0.0943],
        [-0.0726],
        [-0.0521],
        [ 0.0617],
        [-0.2417],
        [ 0.0370],
        [-0.3082],
        [ 0.1710],
        [-0.0245],
        [ 0.2493],
        [-0.1263],
        [ 0.1164],
        [ 0.0536],
        [-0.1267]], dtype=torch.float64, requires_grad=True)

In [77]:
model.bias

tensor([-0.5271], dtype=torch.float64, requires_grad=True)

In [78]:
# model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred >  0.5).float()
    accuracy = ( y_pred == y_test_tensor).float().mean()
print(f'Accuracy: {accuracy.item()}')    



Accuracy: 0.6228070259094238
