In [2]:
import torch
print(torch.__version__)

2.13.0+cpu


In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [4]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: { torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. USing CPU")    

GPU not available. USing CPU


In [7]:
# creating a tensor
a= torch.empty(2,3)
type(a)

torch.Tensor

In [ ]:
# zeros and ones
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
torch.rand(5,6)

tensor([[0.2659, 0.7735, 0.8097, 0.4373, 0.9313, 0.4894],
        [0.1172, 0.2421, 0.8350, 0.8410, 0.4098, 0.1561],
        [0.6652, 0.6488, 0.4702, 0.4921, 0.2340, 0.9223],
        [0.2161, 0.6193, 0.4292, 0.6889, 0.0709, 0.4490],
        [0.6778, 0.3357, 0.1682, 0.8030, 0.4410, 0.8352]])

In [ ]:
# to get same random use manual seed
torch.manual_seed(100)
torch.rand(3,2) 
# rand generate 0 and 1 between float valaues

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839],
        [0.6765, 0.7539]])

In [12]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [15]:
torch.range(0,10,2)
# The primary difference between torch.range and torch.arange is that torch.range is deprecated and includes the end value in its output (inclusive), whereas torch.arange is the modern standard and excludes the end value (exclusive), matching standard Python and NumPy conventions.

C:\Users\sarth\AppData\Local\Temp\ipykernel_29248\1958626597.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10,2)


tensor([ 0.,  2.,  4.,  6.,  8., 10.])

In [18]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [19]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [28]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [29]:
y = torch.tensor([[1,1,2],[3,4,5]])
y.shape

torch.Size([2, 3])

In [ ]:
# to get the same shape like some other tensor, use zeros, ones, empty, rand with dtype
torch.empty_like(y)
torch.zeros_like(y)
torch.ones_like(y)
torch.rand_like(y, dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [31]:
# data types
y.dtype

torch.int64

In [34]:
type = torch.tensor([1.0,2.0,3.0], dtype= torch.int32)


In [35]:
y.to(torch.float32)

tensor([[1., 1., 2.],
        [3., 4., 5.]])

In [39]:
# operations
# scalar operations
a = torch.rand(3,2)

In [ ]:
a + 2 
#  add, sub, mul, div, int div as x//3, mod as % 2, pow as **2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014],
        [2.9969, 2.7565]])

In [ ]:
# more than two tensors element wise operations, pow, mod
b = torch.rand(2,3)
c= torch.rand(2,3)

In [42]:
# add, sub, mul, div,pow, mod 
# extra operations
torch.abs(c)

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])

In [43]:
torch.neg(c)

tensor([[-0.4440, -0.9478, -0.7445],
        [-0.4892, -0.2426, -0.7003]])

In [44]:
torch.round(c)

tensor([[0., 1., 1.],
        [0., 0., 1.]])

In [45]:
torch.ceil(c)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [46]:
torch.floor(c)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [48]:
torch.clamp(c, min=2, max=3)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [49]:
# reduction operation where we reduce a tensor to a single value
# sum
torch.sum(c)

tensor(3.5685)

In [50]:
torch.sum(c, dim=0)

tensor([0.9332, 1.1904, 1.4448])

In [51]:
torch.sum(c, dim=1)

tensor([2.1364, 1.4321])

In [53]:
torch.mean(c)
torch.median(c)
# max, min, prod, std, var,argmax, argmin which tells the position for the max or min value. 


tensor(0.4892)

In [58]:
e = torch.tensor([[1,2,3],[3,4,5]])
f = torch.tensor([[3,3,3],[4,4,4], [5,5,5]])
e @ f
#  or torch.matmul(e,f)


tensor([[26, 26, 26],
        [50, 50, 50]])

In [60]:
torch.dot(e,f) 
# between 1D tensors only

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [63]:
# transpose
torch.transpose(f, 0, 1) 
# transpose(tensor, position, position to be swapped with)

tensor([[3, 4, 5],
        [3, 4, 5],
        [3, 4, 5]])

In [64]:
torch.det(f)
torch.inverse(f)
# only with square function

RuntimeError: linalg.det: Expected a floating point or complex tensor as input. Got Long

In [65]:
# comaprision operaters like >, <, ==, !=, >=, <=
# torch.log
#torch.exp, sigmoid, softmax with dim, relu etc.


In [67]:
# inplace operations
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6476, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.5123]])
tensor([[0.9051, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])


In [68]:
# for each operation performed on tensors, a new tensor is formed. what i want is if i add m with n, value should be stored in m itself.
m.add_(n)
print(m)
print(n)

tensor([[1.5527, 0.9419, 0.7632],
        [1.2539, 0.5009, 0.8512]])
tensor([[0.9051, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])


In [69]:
# similarly you can do the same with relu_...this underscore is inplace operation

In [70]:
# copying the tensors. if you copy something like a = b , changes made in  a with also reflect in b, this is a shalow copy. we want deep copy as well. check with id() function
# instead use clone( like b = a.clone())


In [71]:
# how to perform tensors opn on gpu
torch.cuda.is_available()
device = torch.device("cuda")


In [ ]:
# creating a new tensor on gpu
torch.rand((2,3), device = device)

AssertionError: Torch not compiled with CUDA enabled

In [73]:
# moving existing tensor to gpu
a = torch.rand(2,3)



In [ ]:
b = a.to(device)

AssertionError: Torch not compiled with CUDA enabled

In [75]:
b + 5

tensor([[5.2239, 5.3023, 5.1784],
        [5.8238, 5.5557, 5.9770]])

In [78]:
# reshaping tensors
a.reshape(2,1,1,1)
a.flatten()
a.permute(2,0,1)
# permute is re positioning 


RuntimeError: shape '[2, 1, 1, 1]' is invalid for input of size 6

In [ ]:
# unsqueeze adds a new dimension at the given poosition
z = torch.rand(226,226,3)

In [80]:
z.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [81]:
# squeeze remove the given positions dimension

In [82]:
# convert numpy as pytorch
import numpy as np

In [83]:
a = torch.tensor([1,2,2])


In [84]:
b = a.numpy()

In [85]:
b

array([1, 2, 2])

In [87]:
c = np.array([1,2,3,4])



In [88]:
torch.from_numpy(c)

tensor([1, 2, 3, 4])

In [ ]:
# Direct Comparison
# Feature

# torch.rand 
# torch.randn

# Distribution
# Uniform Distribution \([0, 1)\)
# Standard Normal Distribution (μ=0, σ²=1)

# Value Range
# Always 0 ≤ x < 1
# Theoretically (-∞, ∞), mostly between -3 and 3

# Negative Values
# No
# Yes

# Common Use Case
# Simulating probabilities, random dropout, or adding absolute noise
# Initializing weights in deep neural networks