In [2]:
import torch
print(torch.__version__)

2.13.0+cpu


In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [4]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: { torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. USing CPU")    

GPU not available. USing CPU


In [7]:
# creating a tensor
a= torch.empty(2,3)
type(a)

torch.Tensor

In [ ]:
# zeros and ones
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
torch.rand(5,6)

tensor([[0.2659, 0.7735, 0.8097, 0.4373, 0.9313, 0.4894],
        [0.1172, 0.2421, 0.8350, 0.8410, 0.4098, 0.1561],
        [0.6652, 0.6488, 0.4702, 0.4921, 0.2340, 0.9223],
        [0.2161, 0.6193, 0.4292, 0.6889, 0.0709, 0.4490],
        [0.6778, 0.3357, 0.1682, 0.8030, 0.4410, 0.8352]])

In [ ]:
# to get same random use manual seed
torch.manual_seed(100)
torch.rand(3,2) 
# rand generate 0 and 1 between float valaues

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839],
        [0.6765, 0.7539]])

In [12]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [15]:
torch.range(0,10,2)
# The primary difference between torch.range and torch.arange is that torch.range is deprecated and includes the end value in its output (inclusive), whereas torch.arange is the modern standard and excludes the end value (exclusive), matching standard Python and NumPy conventions.

C:\Users\sarth\AppData\Local\Temp\ipykernel_29248\1958626597.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10,2)


tensor([ 0.,  2.,  4.,  6.,  8., 10.])

In [18]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [19]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [28]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [29]:
y = torch.tensor([[1,1,2],[3,4,5]])
y.shape

torch.Size([2, 3])

In [ ]:
# to get the same shape like some other tensor, use zeros, ones, empty, rand with dtype
torch.empty_like(y)
torch.zeros_like(y)
torch.ones_like(y)
torch.rand_like(y, dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [31]:
# data types
y.dtype

torch.int64

In [34]:
type = torch.tensor([1.0,2.0,3.0], dtype= torch.int32)


In [35]:
y.to(torch.float32)

tensor([[1., 1., 2.],
        [3., 4., 5.]])